### ISSUE TITLE
Proper rejection for  multi-player games invitation

### ISSUE THREAD

**Issue by bihonglu** [yrutschle/DGSLib#2]
This issues was found many months ago by me.  The bots supported by DGSlib would get stuck and stop playing if there are multi-player-game invitation pending. 

Here is DGS discussion link:
http://www.dragongoserver.net/forum/read.php?forum=2&thread=49261

JUG recommended a solution on this:

RE: Bots do not support multi-player games
--
by   JUG (jug), 2k   2017-05-09 11:58   (No. 2)
Then in your bots invitation-filter you better reject invitations with:game_settings.game_type != "GO"

My comments on this issue is that it is a nice feature to have in DGSlib,  but probably is lower priority. After I warned  months ago, no repeating incidents happened. I opened this ticket so that we have a document of this bug.

**Comment by yrutschle** [comment]
Indeed -- I wasn't actually aware of the issue (I don't tend to follow DGS forums at all) so thanks for raising it here. It looks like something that's easy enough to fix, I'll try and look at it in the next few days.

**Comment by yrutschle** [comment]
Done -- I've added  a method to get to the property and modified the qrobot example. It accepts normal games, I havent checked it rejects non-go games as... I don't actually know how you start a team-go game! Can you report if it works? :)
