### ISSUE TITLE
Support for https DGS upgrade? 

### ISSUE THREAD

**Issue by bihonglu** [yrutschle/DGSLib#3]
DGS has an upgrade to use https at:
https://www.dragongoserver.net/forum/read.php?forum=1&thread=50157#50157

Is the change going to work with DGSlib?

**Comment by bihonglu** [comment]
Changed file "DGSQBot.pm" below line:
  $dgs->url('http://www.dragongoserver.net');
to
  $dgs->url('https://www.dragongoserver.net');

So far the https code works well

**Comment by yrutschle** [comment]
I think the LWP library would have followed the redirect to https... I just pushed a patch for this, anyhoo.

**Comment by bihonglu** [comment]
I think JUG is going to remove redirect soon.  Just put msg record of my testing results on oregobot/shorelinebot match.  They worked well after changing to https directly. 

Here are msg with JUG:

Date: | 2018-05-25 04:49
-- | --
From: | JUG (jug)   [ Bulk-Message with other receivers ]
Subject: | [ADMIN]: Bots working with https?
Message: | Hi, just wanted to check with you, if your bots work with the http-to-https redirect I had to put in place? It would be better to configure the bots right away with connecting directly to the SSL-secured URL: https://www.dragongoserver.net/
 Cheers,/

JUG (DGS-Admin)


Date: | 2018-05-26 11:51
-- | --
To: | JUG (jug)
Subject: | RE: [ADMIN]: Bots working with https?
Message:  | Hi JUG, I tested with my bots with new https replacing the old link. It works well. 
Shoreline

**Comment by jug** [comment]
> I think JUG is going to remove redirect soon.

No. The http-to-https redirect stays ... to catch those that still use the unencrypted  access.
It just might be that some clients (libs) cannot cope with the redirect ;-)

But for your bots the issue is solved anyway.
