### ISSUE TITLE
How to make my own lib?

### ISSUE THREAD

**Issue by kennyfs** [yrutschle/DGSLib#4]
I can't read Perl codes well.  
And I want to make my own python or something else version.
Can anyone help me with getting:

>game sgf
>game states like: board size, handicaps.etc

**Comment by yrutschle** [comment]
I am not sure what you expect here... Either wrap DGSLib in Python somehow, or read the API documentation to write your own, I guess: https://sourceforge.net/p/dragongoserver/dgs-main/ci/master/tree/specs/quick_suite.txt

**Comment by kennyfs** [comment]
Thank you.
I didn't understand its way.
I've understood now, and I suggest you to paste the link in the Readme.

yrutschle <notifications@github.com> 於 2019年9月17日 週二 03:37 寫道：

**Comment by yrutschle** [comment]
Fair enough point, done.
